Yengzzkie/instock-client

- src/App.jsx
- src/components/DeleteModal/DeleteModal.jsx
- src/components/Table/Table.jsx
this update will make the modal reusable when both deleting a warehouse and/or deleting an inventory item
> add a function that will handle the text content of modal

- src/components/InventoryTable/InventoryTable.jsx
- src/components/InventoryTable/InventoryTable.scss
- src/pages/WarehousePage/WarehousePage.jsx
- Applied responsiveness to one table instead of making a separate component for mobile view
- Cleaned the responsiveness, removed unnecessary selectors
- Removed <td> inside <th> and replaced it with <span>
- Cleaned .table__warehouse-details' responsiveness
> Hotfix | table responsiveness

- src/main.jsx
Added the following routes:
```
{ path: "/inventory/:id", element: <InventoryPage /> }, // change element here to Inventory Details component
{ path: "/inventory/edit/:id", element: <InventoryEdit /> }
```
Imported the newly created component (InventoryEdit)
`import InventoryEdit from './components/InventoryEdit/InventoryEdit.jsx'`
Note: Refer to branch `feature/O242-15` to check the InventoryEdit component.
> Feature/o242-34 | Added Routes for Inventory

- package-lock.json
- src/components/FormField/FormField.jsx
- src/components/FormField/FormField.scss
- src/components/InventoryEdit/InventoryEdit.jsx
- src/components/InventoryEdit/InventoryEdit.scss
FormField Component
- Fixed bugs (sass file not imported).
- Added the following fields: number, textarea, and radio.
- Changed dropdown type to select.
- Error handling
InventoryEdit Component
- Design only
- Fields uses FormField Component
- Error handling
- Responsiveness
What's next?
- Functionality (api calling) - Still waiting for the api endpoint
**IMPORTANT: Ensure merging PR `#19` first before merging this.**
> Feature/o242-15 | Client: Edit Inventory Item page

- .env.example
- src/App.scss
- src/components/AddNewWarehouse/AddNewWarehouse.jsx
- src/components/FormField/FormField.jsx
- src/components/FormField/FormField.scss
- src/components/InventoryEdit/InventoryEdit.jsx
- src/components/InventoryEdit/InventoryEdit.scss
- src/components/WarehouseEdit/WarehouseEdit.scss
- src/components/WarehouseList/WarehouseList.jsx
- Adjusted main__containers min and max height
- Added vite_port to make it dynamic
- Added font-weight to label
- Removed font weight for label and moved it Form Field to make it accessible to all components
- Added container background
- Sample .env file for front-end
> Hotfix | Fixing minor bugs

- src/components/ItemDetails/ItemDetails.jsx
- removed the API call for getting the warehouse details since warehouse_name has already been incorporated from backend
- removed useLocation() in itemDetails as it is no longer necessary here as well sincce warehouse_name is items details response
> fix: removed unnecessary API call for

- src/components/FormField/FormField.jsx
- src/components/FormField/HandleError.jsx
- src/components/InventoryEdit/InventoryEdit.jsx
- src/components/InventoryEdit/InventoryFields.json
- Created json file for all the Inventory Item fields
- Updated json file. Categories and Warehouses are now retrieving data dynamically
- Updated instruction on how to use the component
- Created a new jsx file to perform error handling on the inputs dynamically
- Fields are autopopulated. 
- Fetched all the Warehouses using api. 
- Quantity field is hidden based on status. 
- Categories field is still set to static. 
- Fully functional from error handling to retrieving data
What's next?
- retrieving categories using api
- updating data upon submitting the form
Backlog:
- waiting for the endpoint of `/categories` and updating inventories data
> Feature/o242-15 | Fully functional form

- src/components/InventoryEdit/InventoryEdit.jsx
From: 
```
setInventoryItem(response.data[0]);
```
To
```
setInventoryItem(response.data);
```
> Quick fixed fetching inventory data on the InventoryEdit component

- src/components/AddNewWarehouse/AddNewWarehouse.scss
- src/components/WarehouseEdit/WarehouseEdit.jsx
- src/components/WarehouseEdit/WarehouseEdit.scss
Updated SCSS for ADD NEW WAREHOUSE and EDIT WAREHOUSE for mobile
> Updated SCSS for ADD NEW WAREHOUSE and EDIT WAREHOUSE for mobile

- src/components/InventoryTable/InventoryTable.jsx
- src/components/ItemDetails/ItemDetails.jsx
changed the PORT variable to VITE_PORT
> fixed the PORT variable in the ItemDetails and inventoryTable

- src/components/InventoryTable/InventoryTable.jsx
- src/components/ItemDetails/ItemDetails.jsx
- added route to Inventory Edit page and Warehouse Edit page when the Edit button is clicked.
> add routes to InventoryEdit and WarehouseEdit

- src/components/WarehouseEdit/WarehouseEdit.jsx
Had to change some routing name conventions: warehouseID to ID.
> Sucessfully made EDITING and PATCHING request functionality

- src/components/EditButton/EditButton.jsx
- src/components/EditButton/EditButton.scss
- src/components/InventoryTable/InventoryTable.jsx
- src/components/InventoryTable/InventoryTable.scss
- src/components/ItemDetails/ItemDetails.jsx
- src/components/ItemDetails/ItemDetails.scss
- Created a reusable <EditButton /> component to improve maintainability and consistency across different pages.
- added mobile style for the Edit Button
> created a new EditButton component

- src/App.scss
- src/components/Navigation/Navigation.scss
Adjusted styling for MOBILE: EDIT WAREHOUSE COMPONENT to match the styling in FIGMA, also fixed the nav styling: made WAREHOUSE and INVENTORY buttons span the width of the app in MOBILE
> Mobile styling updates: EDIT WAREHOUSE COMPONENT + NAV 

- src/App.scss
- src/components/InventoryTable/InventoryTable.scss
- src/components/WarehouseList/WarehouseList.jsx
- src/components/WarehouseList/WarehouseList.scss
- Transformed 2 tables (desktop and mobile) into 1 table
- Added fixed table-layout to prevent table from overflowing the container
- Fixing the header of the warehouse container
> Hotfix | Fixed Warehouse styling

- src/App.scss
- src/components/Footer/Footer.scss
- fixed the position of Footer to the bottom of the page
- added min-height 100vh to app_wrapper class to accommodate the position of the Footer
> fixed footer to bottom of the page

- src/components/InventoryForm/InventoryForm.scss
- src/main.jsx
- src/pages/AddNewInventoryPage/AddNewInventoryPage.jsx
- fixed import error on main.jsx for AddNewInventoryPage
- removed bottom property for back arrow svg in outlet nav causing misalignment
> Hotfix for feat/O242-17

- package-lock.json
- package.json
- src/App.jsx
- src/App.scss
- src/components/AddNewWarehouse/AddNewWarehouse.jsx
- src/components/DeleteModal/DeleteModal.jsx
- src/components/Footer/Footer.scss
- src/components/InventoryTable/InventoryTable.jsx
- src/components/InventoryTable/InventoryTable.scss
- src/components/WarehouseEdit/WarehouseEdit.jsx
- src/components/WarehouseList/WarehouseList.jsx
- added toastify for notifications
- set app_wrapper min height to 100vh to accommodate Footer position to bottom
- reduced padding on inventory table navbar on mobile screens
> - added toastify for notifications

- src/components/InventoryTable/InventoryTable.jsx
- set the displayed quantity to 0 if the item is set to out of stock regardless if database has quantity
> fixed instock/outofstock rendering

- src/components/InventoryEdit/InventoryEdit.jsx
- src/components/WarehouseList/WarehouseList.jsx
- src/components/WarehouseList/WarehouseList.scss
- src/pages/AddNewInventoryPage/AddNewInventoryPage.jsx
fixed back button for EDIT INVENTORY ITEM to go back to the previous page, NOT the INVENTORY LIST
> INVENTORY EDIT: back button fix

- src/components/DeleteModal/DeleteModal.jsx
removed double ?? from delete dialogue box.
> Removed double ?? from DELETE module

- src/components/WarehouseList/WarehouseList.jsx
Updated link from WAREHOUSE EDIT COMPONENT to EDIT WAREHOUSE = warehouse/edit/{$id}
> Updated EDIT WAREHOUSE link

- src/components/FormField/FormField.jsx
- src/components/InventoryForm/InventoryForm.jsx
- src/components/InventoryForm/InventoryForm.scss
- Added proper navigation link to the Back button in the InventoryForm
- Updated FormField components to use value instead of defaultValue to maintain controlled input behavior
- Adjusted footer button styling in InventoryForm to match the design mockups
- Selecting In Stock or Out of Stock will now dynamically update the quantity field, setting it to the existing amount for In Stock, or resetting it to 0 for Out of Stock.
> Fixes and updates on inventoryForm

- src/components/AddNewWarehouse/AddNewWarehouse.jsx
- src/components/AddNewWarehouse/AddNewWarehouse.scss
- src/components/WarehouseEdit/WarehouseEdit.jsx
- src/pages/WarehousePage/WarehousePage.jsx
- src/styles/partials/_fonts.scss
- src/styles/partials/_global.scss
- src/styles/partials/_mixins.scss
1. REMOVED all code and comments that are not necessary
2. KEPT all comments that describe functions.
> Code clean up

- src/components/InventoryTable/InventoryTable.jsx
- src/pages/InventoryPage/InventoryPage.jsx
toastify added to delete inventory item and rendering of out of stock… on inventory table
> last minute changes
